[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
all_your_keys_are_belong_tous = "BjQ3BpvtHL6oLjGRQZbdpc5p4U5phJFrQLYWQLJQSyAC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/jd/7i.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
